### ISSUE TITLE
Template rule

### ISSUE THREAD

**Issue by nyx0** [Yara-Rules/rules#2]
I think you should provide an rule template for contributions, like this one:
```
rule test : tag
{
	meta:
		Author		= "author"
		Date		= "yyyy/mm/dd"
		Description	= "Strings inside"
		Reference	= "Link to the blog, paper..."
}
```

**Comment by 9b** [comment]
Adding to this, I would also say to standardize on the template and say all lowercase for meta rules. Additionally, you may want to add the following to the meta data:
* share_level (follow TLP)
* sample (any file hash that would be matched)
* source (i.e., organization the author supports)

Lastly, it could be worth outline a subset of rule prefix names depending on what they are serving. For instance, shellcode detection could be "rule shellcode_<more specific>".

**Comment by nyx0** [comment]
Yes for all meta in lowercase, but after in my opinion TLP is not gonna be interesting because all rules committed are at least TLP white, maybe green.
**sample**: hashes can be present, but some blog post are revealing yara rule whitout hashes, so it cannot be a default value but an optional.
**source**: in most cases the reference meta is a link to a blogpost/report made by the organization, do you think it's worth it to add another field to put it?

**Comment by jovimon** [comment]
I agree with nyx0 regarding TLP of rules as github is open to everyone.

Also, regarding the prefix names 9b mentioned, wouldn't it be better to use Tags? You could run only a specific subset of rules just from commandline. An example taken from [Yara documentation](https://yara.readthedocs.org/en/v3.3.0/commandline.html) 
> Apply rules on /foo/bar/rules to bazfile. Only reports rules tagged as Packer or Compiler:
> yara -t Packer -t Compiler /foo/bar/rules bazfile

**Comment by 9b** [comment]
Yes, these rules are public, but it's likely that those consuming these rules will have their own rules pre-defined. It would be nice to associate the TLP just so as they slowly move from this repository and into other organizations, that it's share level is understood.

In regards to prefixes, tags could replicate the functionality, but standardizing the rule prefix ensure you don't get rules with useless names like "rule magicFlyParseCheckMutexLoad". Having some standard, even if it's pretty generic, could help in the long run. 

A final suggestion could be to split the rules out into different files based on function. The present single file is good for sharing, but could get a little messy if multiple people started submitting pull requests all at once. It's also difficult to identify what the current rule file provides coverage for since it's so large.

**Comment by yararules** [comment]
9b, we are thinking like to split the rules. It's difficult to manage the pull requests over one file. We are thinking one file by malware family, for example.

**Comment by jovimon** [comment]
I get 9b's point and agree on adding TLP and prefixes can help us classify rules as well as tags.

So far we have this:
```
rule prefixed_test : tag1 tag2 tag3
{
    meta:
        author      = "author's name and (if possible) link to profile"
        date        = "yyyy/mm/dd"
        description = "What does the rule do"
        reference/source = "Link to the blog, paper, ..."
        sample      = "file hashes"
        tlp         = "red/amber/green/white"
}
```
Anything else that might be useful?
