### ISSUE TITLE
"Private Global" preventing index.yar and malware_index.yar from working correctly

### ISSUE THREAD

**Issue by VVinner38** [Yara-Rules/rules#307]
Files:
malware/RAT_CrossRAT.yar
malware/MALW_TRITON_HATMAN.yar

It prevents all rules to trigger if the file size condition is not true.
I added the private global condition of each file in the other rules of the file and removed the private global condition.

**Comment by teoring** [comment]
I have faced this problem. Basically nothing was matched when those files were in index.

**Comment by teoring** [comment]
Actually I am still facing this problem even with private global condition. 
I downloaded the database, unpacked and run generate index script. To test the rules I am doing a matching against a files in the database itself.

`yara -r -w index.yar  
`
returns no match while email_index, which in fact included in index.yar is able to find a matches:

`yara -r -w email_index.yar  
`
The problem was narrowed down to the include of the RAT_CrossRAT. Once it was excluded from the index.yar matching work fine once again.

**Comment by jholgui** [comment]
We modified RAT_CrossRAT.yar and MALW_TRITON_HATMAN.yar. I think that the problem is solved. 
I close the ticket.
