### ISSUE TITLE
clamav integration

### ISSUE THREAD

**Issue by JayBrown** [Yara-Rules/rules#80]
How do I go about integrating yara rules with clamav? I have compiled clamav with the yara option, and the clamav documentation says to simply put the .yar files into /usr/local/share/clamav/ … and then run clamscan or clamdscan as before, while the yara rules will be automatically included.

However, with some .yar files I get regular error messages, e.g.:

LibClamAV Error: yyerror(): /usr/local/Cellar/clamav/0.99/share/clamav/antidebug.yar line 497 undefined identifier "pe"
LibClamAV Error: yyerror(): /usr/local/Cellar/clamav/0.99/share/clamav/packer.yar line 439 undefined identifier "pe"
LibClamAV Error: cli_loadyara: failed to parse rules file /usr/local/Cellar/clamav/0.99/share/clamav/packer.yar, error count 1396

What's that all about?

**Comment by jovimon** [comment]
Hello JayBrown,

This errors appear because ClamAV cannot find the Yara's PE module.

I've searched through the [ClamAV documentation](https://github.com/vrtadmin/clamav-devel/blob/master/docs/signatures.pdf) (section 3.11 Using YARA rules in ClamAV) and they say integration of both tools is still new and some features, like usage of Yara modules, are not yet supported.

I'm afraid you'll have to wait for ClamAV developers to get a full integration of ClamAV with Yara, or load only rules that don't use any module.
